# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  #schedule:
  #  - cron:  '30 5,17 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Get software list
        run: |
           curl -s https://raw.githubusercontent.com/coolsnowwolf/lede/master/README.md | sed -n '/sudo apt install -y/,/```/p' >> list1
           sed -i 's/   //g' list1
           sed -i 's/```//g' list1
           sed -i 's/sudo apt install -y //g' list1
           sed -i 's/\\//g' list1
           cat list1 | tr -d '\n' > list2
           echo '' >> list2
           cat list2
           cat ubuntu
           cat list2 > ubuntu
           rm list1
           rm list2
      - name: git push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Update apt list"
          git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/Plutonium141/openwrt-depends-ubuntu.git"
           
           
